### PR TITLE
Improve Git/HTTPS URL generation

### LINKED ISSUE #777: [BUG] Cannot configure SSH git
**Describe the bug**
When configuring git with SSH I enter the following information (personal information redacted):
* Username: `git`
* Server URL: `ssh.example.com`
* Port: `EMPTY`
* Repo path: `:passwords.git` OR `passwords.git` (both fail)
* Authentication Mode: SSH or OpenKeyChain. I didn't attempt password since I don't want to allow that in my repository.

When I press "Clone" it returns an error like
```
Error occurred during the clone operation, Message from jgit:
Invalid remote: origin
Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException: ssh://git@ssh.example.com/:passwords.git: fatal: '/:passwords.git' does not appear to be a git repository
```

You will notice that it adds a `/` at the start of the repo path, probably from here: https://github.com/android-password-store/Android-Password-Store/blob/041cf00510a75042223d1857660fc7f1dff958ef/app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt#L98

**To Reproduce**
1. Enter the data I did above.
2. Press "Clone"
3. See the error

**Expected behavior**
The repository should be successfully cloned.

**Device information (please complete the following information):**
 - Device: OnePlus 8 Pro
 - OS: Oxygen OS 10.5.6.IN11AA
 - App version: 1.7.2

**Additional context**
This worked with the older version of the application, but I am setting this up on a new phone and encountered this today.

Additionally, this happens with both an SSH key generated in-app and copied on to the server as well as with an OpenKeyChain GPG authentication key.

Finally, I tested this on my machine with `git clone git@ssh.example.com:passwords.git` and it successfully clones the repository.

### PR DESCRIPTION
**Pull request by FabianHenneke**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring

## :scroll: Description

Improve the generation of the Git/HTTPS repo URL from its parts in multiple ways:

* Strip the "ssh://" prefix if somebody entered it
* Use the ssh:// scheme if there is a custom port
* Apply the URI verification only to HTTPS
* Trim trailing @s from the user part

## :bulb: Motivation and Context

Should fix #777.

## :green_heart: How did you test it?
I tried some variations, but have not been able to test HTTPS and SSH with custom ports. Please do if you can.

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code

### CODE REVIEW

**Comment by msfjarvis** [comment]
When using a custom port we should probably enforce a non-relative path (check if it starts with '/' should suffice) since those won't work without it.

**Comment by FabianHenneke** [comment]
> When using a custom port we should probably enforce a non-relative path (check if it starts with '/' should suffice) since those won't work without it.

Is this fine or would we need a custom error message if somebody leaves out the `/`?

**Comment by msfjarvis** [comment]
> > When using a custom port we should probably enforce a non-relative path (check if it starts with '/' should suffice) since those won't work without it.
> 
> Is this fine or would we need a custom error message if somebody leaves out the `/`?

We're gonna need a proper error message here since the fix is rather non-obvious.

**Comment by FabianHenneke** [comment]
> > > When using a custom port we should probably enforce a non-relative path (check if it starts with '/' should suffice) since those won't work without it.
> > 
> > 
> > Is this fine or would we need a custom error message if somebody leaves out the `/`?
> 
> We're gonna need a proper error message here since the fix is rather non-obvious.

This would probably require introducing an error enum to return from `upateUrl()`. What about the alternative of simply prepending a slash if the path doesn't start with one?

**Comment by msfjarvis** [comment]
> > > > When using a custom port we should probably enforce a non-relative path (check if it starts with '/' should suffice) since those won't work without it.
> > > 
> > > 
> > > Is this fine or would we need a custom error message if somebody leaves out the `/`?
> > 
> > 
> > We're gonna need a proper error message here since the fix is rather non-obvious.
> 
> This would probably require introducing an error enum to return from `upateUrl()`. What about the alternative of simply prepending a slash if the path doesn't start with one?

It'd still fail, `foo` being resolved to `~/foo` as a relative path and to `/foo` when we add a slash ourselves is going to create the same problem I described.

**Comment by FabianHenneke** [comment]
I added specific error messages for the error cases we could already distinguish.

**Pull request merged**
