### PR TITLE
Gain focus in folder creation dialog

### PR DESCRIPTION
**Pull request by msfjarvis**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring

## :scroll: Description
Open the keyboard and gain focus on the folder name textview to improve UX.

## :bulb: Motivation and Context
Currently we need to click on the textview manually to start writing the name for a folder which is rather cumbersome. Automatically gaining focus
will improve this flow.

## :green_heart: How did you test it?
Untested as of now, probably will not even compile.

## :pencil: Checklist

- [ ] I ran `./gradlew spotlessApply` before submitting the PR
- [ ] I reviewed submitted code

### CODE REVIEW

**Comment by msfjarvis** [comment]
The folder dialog is very user unfriendly without this so this *needs* to go out with v1.5.0 next month.

**Comment by Skrilltrax** [comment]
Need some help 👩‍🔧

**Comment by msfjarvis** [comment]
> Need some help

You think? :roll_eyes:

**Comment by Skrilltrax** [comment]
Will take a look at it today :wrench:

**Comment by Skrilltrax** [comment]
This most definitely feels like a hack but currently it's the only way i can bring-up keyboard after dialog creation. Even after giving focus to the edit text the keyboard does not seems to work as it should. Feel free to revert it if you find any other way or if it does not seem right.

**Comment by msfjarvis** [comment]
> This most definitely feels like a hack but currently it's the only way i can bring-up keyboard after dialog creation. Even after giving focus to the edit text the keyboard does not seems to work as it should. Feel free to revert it if you find any other way or if it does not seem right.

That's the most annoying thing — it shouldn't be this hard! This class originated in [Viscerion](https://github.com/msfjarvis/viscerion/blob/master/app/src/main/java/com/wireguard/android/fragment/ConfigNamingDialogFragment.kt) where no such hacks are involved and everything works just fine :/

**Comment by msfjarvis** [comment]
@Skrilltrax I'm absolutely clueless so let's just merge this as-is and revisit when we either of us has spare time.

**Comment by Skrilltrax** [comment]
Sure

**Comment by msfjarvis** [comment]
image

:tada:

**Pull request merged**
