### PR TITLE
Bump version for new listing

### PR DESCRIPTION
**Pull request by msfjarvis**
Pending publication at https://play.google.com/store/apps/details?id=dev.msfjarvis.aps

@zeapo can you please redirect users from the current listing?

### CODE REVIEW

**Comment by msfjarvis** [comment]
Reviewers: Do not squash this when merging, prefer a fast-forward push.

**Comment by msfjarvis** [comment]
Listing isn't live yet so let's wait for that

**Comment by Skrilltrax** [comment]
Sure

**Comment by msfjarvis** [comment]
The Play Store listing is now live. Mohamed asked for a few days to get on top of things so I'll let him do the final build on his timeline and kickstart the next phase of development over here.

**Pull request merged**
