### PR TITLE
WIP: Maybe fix symbolic link handling in JGit

### PR DESCRIPTION
**Pull request by FabianHenneke**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :pencil: Checklist

- [ ] I ran `./gradlew spotlessApply` before submitting the PR
- [ ] I reviewed submitted code

### CODE REVIEW

**Comment by msfjarvis** [comment]
R8 chokes when trying to compile this, trying without it.

**Comment by msfjarvis** [comment]
Doesn't work :(

**Comment by FabianHenneke** [comment]
> R8 chokes when trying to compile this, trying without it.

It worked for me (Android Studio 3.6.3) and the CI, which makes this quite mysterious. Maybe try invalidating your caches and rebuilding from scratch?

**Comment by FabianHenneke** [comment]
> Doesn't work :(

As in doesn't compile or doesn't fix the issue? I guess it was worth trying, but in case of the latter I'm out of ideas on how to fix this...

**Comment by msfjarvis** [comment]
> > R8 chokes when trying to compile this, trying without it.
> 
> It worked for me (Android Studio 3.6.3) and the CI, which makes this quite mysterious. Maybe try invalidating your caches and rebuilding from scratch?

Debug builds don't use R8, and CI doesn't compile release. I was building release for my main device.

> > Doesn't work :(
> 
> As in doesn't compile or doesn't fix the issue? I guess it was worth trying, but in case of the latter I'm out of ideas on how to fix this...

Doesn't fix the issue. Disabling minify allowed the build to succeed.

**Comment by FabianHenneke** [comment]
> Debug builds don't use R8, and CI doesn't compile release. I was building release for my main device.

Oh, I missed that... This makes me think: Should we switch CI over to do the release build for us? Or maybe both debug/release in a new matrix build?

**Comment by msfjarvis** [comment]
> > Debug builds don't use R8, and CI doesn't compile release. I was building release for my main device.
> 
> Oh, I missed that... This makes me think: Should we switch CI over to do the release build for us? Or maybe both debug/release in a new matrix build?

Matrix seems more reasonable. `master` pushes generate release builds so it certainly would be nice to be able to catch those problems.

**Pull request closed without merging**
