### PR TITLE
Also run unit tests for release build

### PR DESCRIPTION
**Pull request by FabianHenneke**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring

## :scroll: Description

Runs release builds and lint on every PR.

## :bulb: Motivation and Context

https://github.com/android-password-store/Android-Password-Store/pull/719#issuecomment-615906040

## :pencil: Checklist

- [ ] I ran `./gradlew spotlessApply` before submitting the PR
- [ ] I reviewed submitted code

### CODE REVIEW

**Comment by FabianHenneke** [comment]
> Taking bets on how many hours this takes

We've got ourselves a pretty big matrix here. Let's give it a try and get rid of it if it should prove to be too annoying.

**Comment by msfjarvis** [comment]
> > Taking bets on how many hours this takes
> 
> We've got ourselves a pretty big matrix here. Let's give it a try and get rid of it if it should prove to be too annoying.

The emulators take forever to boot :/ Honestly we should probably drop the entire emulator matrix and only run it on API 23 since that's the easiest to break due to not having Java 8 APIs.

**Comment by FabianHenneke** [comment]
> The emulators take forever to boot :/ Honestly we should probably drop the entire emulator matrix and only run it on API 23 since that's the easiest to break due to not having Java 8 APIs.

Since four runs seem to complete within <= 7mins, how about building Release/Debug on 23/29 as a compromise?

**Comment by msfjarvis** [comment]
> > The emulators take forever to boot :/ Honestly we should probably drop the entire emulator matrix and only run it on API 23 since that's the easiest to break due to not having Java 8 APIs.
> 
> Since four runs seem to complete within <= 7mins, how about building Release/Debug on 23/29 as a compromise?

Can live with that :+1:. Will have to remember to update branch protection rules again to require the new checks when this is merged.

**Comment by FabianHenneke** [comment]
> Can live with that . Will have to remember to update branch protection rules again to require the new checks when this is merged.

Done. I also enabled "Require linear history" and "Include administrators" since that seems to match our workflow, but feel free to change them back if they annoy you. ;-)

**Comment by msfjarvis** [comment]
> > Can live with that . Will have to remember to update branch protection rules again to require the new checks when this is merged.
> 
> Done. I also enabled "Require linear history" and "Include administrators" since that seems to match our workflow, but feel free to change them back if they annoy you. ;-)

Oh that's perfect 👌

**Pull request merged**
