### PR TITLE
Make preferred directory structure for Autofill configurable

### LINKED ISSUE #657: [BUG] Username is not deduced from name of folder with new autofill
**Describe the bug**
(Disclaimer: I didn't use the previous accessibility-based autofill, so this might have been a problem back then as well.)

I just installed the snapshot that includes the new Oreo Autofill from #653. So far, it's great! The only complaint I have is that it uses the name of the file to autofill the username and password. Here's an example of my structure:

```
.password-store
`-- Internet
     `-- github.com
          `-- cole-h
               `-- password
```

However, when I search for autofill entries on `github.com`, it only shows the `password` file (and then fills in the username as `password`, while reading the password from the file).

**To Reproduce**
1. Go to `github.com/login`
2. Search for entries to autofill
3. Tap the `password` file of the `cole-h` entry
4. Note that it fills the username as `password`

**Expected behavior**
I expect autofill to be able to take the name of the parent folder as the username, and the contents of the `password` file as the password. The best way to do this would probably be a setting (or maybe not; I have no experience with mobile app development).

**Screenshots**
Screenshot_20200324-110339_Firefox Nightly

**Device information (please complete the following information):**
 - Device: Galaxy S9
 - OS: One UI 2.0, Android 10
 - App version: latest snapshot as of 24 March 2020 at 10:57AM PDT

### PR DESCRIPTION
**Pull request by FabianHenneke**
## :loudspeaker: Type of change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description

Some users keep their password files in a directory structure such as `/example.org/john@doe.org.gpg` while others prefer the style `/example.org/john@doe.org/password.gpg`.

This commit adds a setting that allows to switch between the two. All Autofill operations, such as search, match, generate and save, respect this setting. Along the way, the suggested path for Autofill save and generate operations has now been made editable.

Note: The first style seems to be the most widely used and is therefore kept as the default. The second style is mentioned on the [official Pass website](https://www.passwordstore.org/#organization). 

## :bulb: Motivation and Context

Fixes #657.

## :green_heart: How did you test it?
I went through all Autofill operations in both modes. Since this is a bigger change, I would like to ask for help in testing.

## :pencil: Checklist

- [x] I ran `./gradlew spotlessApply` before submitting the PR
- [x] I reviewed submitted code

## :camera_flash: Screenshots / GIFs

Screenshot_20200325-124049
Screenshot_20200325-124055

### CODE REVIEW

**Comment by msfjarvis** [comment]
I haven't looked at the code yet but off the bat I'm seeing two bugs that may or may not be related to this PR.

1) "Search in store" option seems to not actually show results until I manually edit the search query in the text field. Seems like `doOnTextChanged` is letting us down?

<details><summary>Screenshot</summary>

image

</details>

2) If I let Password Store autofill for me, then proceed to delete the username manually, the suggested value says "PLACEHOLDER" but when I click on it, the correct username gets filled.

<details><summary>Screenshot</summary>

image

</details>

**Comment by cole-h** [comment]
The only reason I chose this database structure was because of the recommendation on the official website :P

---

@msfjarvis I can't reproduce your second issue, because after deleting the username (in both Firefox Stable and Firefox Nightly Preview), I no longer get to select an entry to autofill, and there is no action to force this. Back when I used Keepass2Android, I believe their implementation had a way to force-detect an input box through a touch-and-hold menu button (insert actual technical jargon here). For the record, this issue is also present in the original PR.

<details><summary>Screenshot incoming</summary>
...
</details>

As for your first issue, I experienced that as well, but only on the original PR. On this branch, entries populate immediately upon tapping the "search in store" button (I'd show you a screenshot, but... well, you'll just have to take my word for it).

**Comment by msfjarvis** [comment]
> The only reason I chose this database structure was because of the recommendation on the official website :P
> 
> @msfjarvis I can't reproduce your second issue, because after deleting the username (in both Firefox Stable and Firefox Nightly Preview), I no longer get to select an entry to autofill, and there is no action to force this. Back when I used Keepass2Android, I believe their implementation had a way to force-detect an input box through a touch-and-hold menu button (insert actual technical jargon here). For the record, this issue is also present in the original PR.

That's weird, I consistently get the buggy option.

> As for your first issue, I experienced that as well, but only on the original PR. On this branch, entries populate immediately upon tapping the "search in store" button (I'd show you a screenshot, but... well, you'll just have to take my word for it).

Yeah like I edited it later, I got it once and not again so I believe it was a case of me running a different build than I thought I was.

> ETA: Otherwise, yes, this feature works perfectly. Thanks for tackling it so quickly @FabianHenneke!

:rocket:

**Comment by FabianHenneke** [comment]
> I haven't looked at the code yet but off the bat I'm seeing two bugs that may or may not be related to this PR.
> 
> 1. "Search in store" option seems to not actually show results until I manually edit the search query in the text field. Seems like `doOnTextChanged` is letting us down? (Edit: This bug scenario appears to be flaky, I can't reproduce it every time.)

Note that the initial search (the one done before you change anything in the filter field) is very strict. It will only find files which, depending on your preferred directory structure, are in a folder or a subfolder of a folder with its name a subdomain of the search term. This is meant as a phishing protection even when 

In particular, if you just tried a different directory structure setting, it may be the case that no file in your repository matched this strict check using the new structure. If it should turn out that this is not the issue here, I will continue to investigate other possible causes.

> 2. If I let Password Store autofill for me, then proceed to delete the username manually, the suggested value says "PLACEHOLDER" but when I click on it, the correct username gets filled.

This is very weird. "PLACEHOLDER" is only used in one place: Since older Android versions do not allow returning an Autofill Dataset without a RemoteViews after authentication, I am using the usual one as a dummy with this value for the TextViews. But returning a Dataset instead of a FillResponse is explicitly documented to lead to a fill instead of showing any UI, so I have no idea how this could end up being shown to you.

May I ask which version of Android/phone model/browser you are testing this in?

> FWIW, the feature introduced in this PR seems to work correctly so if you want I can review this and you can tackle the bugs separately.

That seems reasonable, I will open up another issue/PR as needed to fix the bug.

> I can't reproduce your second issue, because after deleting the username (in both Firefox Stable and Firefox Nightly Preview), I no longer get to select an entry to autofill, and there is no action to force this. Back when I used Keepass2Android, I believe their implementation had a way to force-detect an input box through a touch-and-hold menu button (insert actual technical jargon here).

In apps, this is possible via the Autofill action shown in that touch-and-hold menu (I myself don't know that it is called). The support for filling into any kind of field via this action has just landed as #662. Offering this in browsers that don't support it themselves is unfortunately not possible with the Autofill API, I believe that Keepass2Android was relying on the old Accessibility API for this.

**Comment by msfjarvis** [comment]
> > I haven't looked at the code yet but off the bat I'm seeing two bugs that may or may not be related to this PR.
> > 
> > 1. "Search in store" option seems to not actually show results until I manually edit the search query in the text field. Seems like `doOnTextChanged` is letting us down? (Edit: This bug scenario appears to be flaky, I can't reproduce it every time.)
> 
> Note that the initial search (the one done before you change anything in the filter field) is very strict. It will only find files which, depending on your preferred directory structure, are in a folder or a subfolder of a folder with its name a subdomain of the search term. This is meant as a phishing protection that applies even when there haven't been any matches for this origin yet.
> 
> In particular, if you just tried a different directory structure setting, it may be the case that no file in your repository matched this strict check using the new structure. If it should turn out that this is not the issue here, I will continue to investigate other possible causes.

I think that's exactly the cause in my situation.

> 
> > 1. If I let Password Store autofill for me, then proceed to delete the username manually, the suggested value says "PLACEHOLDER" but when I click on it, the correct username gets filled.
> 
> This is very weird. "PLACEHOLDER" is only used in one place: Since older Android versions do not allow returning an Autofill Dataset without a RemoteViews after authentication, I am using the usual one as a dummy with this value for the TextViews. But returning a Dataset instead of a FillResponse is explicitly documented to lead to a fill instead of showing any UI, so I have no idea how this could end up being shown to you.
> 
> May I ask which version of Android/phone model/browser you are testing this in?

I am on Android R DP2 on my Pixel 2, running Chrome Canary `83.0.4095.0`.

**Comment by FabianHenneke** [comment]
> I think that's exactly the cause in my situation.

If you find the default behavior confusing, we can of course discuss changing (or explaining) it.

> I am on Android R DP2 on my Pixel 2, running Chrome Canary `83.0.4095.0`.

Living on the edge, I see. ;-) Although I am not certain, I suspect that this might be a bug in the preview. I know that Autofill is undergoing some changes in Android R specific to the presentation of datasets (inline presentation becomes available), so this might actually be it. You might want to report this on the Android Issue Tracker and see how it fares there.

**Comment by FabianHenneke** [comment]
@msfjarvis Could you try whether https://github.com/FabianHenneke/Android-Password-Store/commit/490e3e9fda5519fc7094a37f0a989a595153e889 helps with the placeholder dataset issue you are seeing on Android R DP2?

**Comment by msfjarvis** [comment]
> @msfjarvis Could you try whether [FabianHenneke@490e3e9](https://github.com/FabianHenneke/Android-Password-Store/commit/490e3e9fda5519fc7094a37f0a989a595153e889) helps with the placeholder dataset issue you are seeing on Android R DP2?

I don't see any entries now so I suppose that qualifies as fixed?

**Comment by FabianHenneke** [comment]
> I don't see any entries now so I suppose that qualifies as fixed?

That depends, are you not seeing any entries after you have successfully filled the form? In that case, probably yes.

**Comment by msfjarvis** [comment]
> > I don't see any entries now so I suppose that qualifies as fixed?
> 
> That depends, are you not seeing any entries after you have successfully filled the form? In that case, probably yes.

I filled the form, then proceeded to start backspacing the username field one character at a time. Before this fix, I'd get a placeholder entry as soon as I deleted the first character. With the commit applied, I don't get an entry (valid non-placeholder) until the field is empty again.

**Pull request merged**
