### PR TITLE
Resolve symlinks before decryption

### LINKED ISSUE #636: [BUG] symlinks are clobbered by the app
**Describe the bug**
A password will fail to decrypt if it is a soft link as opposed to a normal file.

**To Reproduce**
1. Create a password that's a soft link to an existing password using `ln -s <passwd>.gpg softlink.gpg`
2. Pull the repository on device
3. Try to decrypt the password

**Expected behavior**
Password is decrypted and shown in the UI

**Device information (please complete the following information):**
 - Device: Google Pixel 2
 - OS: Android R DP1
 - App version 1.6.0-SNAPSHOT

**Additional context**

Relevant log snippet

```
E  onError getErrorId: 0
E  onError getMessage: No valid OpenPGP encrypted or signed data found!
```

### PR DESCRIPTION
**Pull request by FabianHenneke**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description

Resolves symlinks before decryption via `File.toRealPath()` if
available (Oreo and later) and otherwise falls back to the `realpath`
GNU coreutil.

## :bulb: Motivation and Context

Hopefully resolves #636 on all API levels.

## :green_heart: How did you test it?
I confirmed that both branches return the correct path for files that are not symbolic links. Since I seem to be unable to get actual symbolic links on my phone, I would ask you to test that it does the right thing on both branches for symbolic links.

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code

### CODE REVIEW

**Comment by msfjarvis** [comment]
The actual symlink is a secondary problem, the real issue is that JGit clobbers the symlink entirely. Rather than `foo/a.gpg` being a symlink to `bar/b.gpg`, it becomes a text file containing the text `bar/b.gpg`. @Dioxo also found this during our discussion back in April.

The only "fix" proposed so far is to read the entire text of a password file as a UTF-8 string and see if the string is the path to a password file, relative to the location of our initial file.

**Comment by msfjarvis** [comment]
On my PC

```
$ file me@msfjarvis.dev.gpg 
me@msfjarvis.dev.gpg: symbolic link to msfjarvis@gmail.com.gpg
```

On my phone
```
walleye:/data/data/dev.msfjarvis.aps/files/store/personal/google.com # file me@msfjarvis.dev.gpg
me@msfjarvis.dev.gpg: ASCII text
walleye:/data/data/dev.msfjarvis.aps/files/store/personal/google.com # cat me@msfjarvis.dev.gpg && echo
msfjarvis@gmail.com.gpg

```

**Comment by FabianHenneke** [comment]
I see, sorry for bringing this up again in that case. I thought that someone in that thread had managed to create an actual symlink, but then decryption still failed, which this commit could resolve. But that doesn't seem to be the case.

**Comment by msfjarvis** [comment]
> I see, sorry for bringing this up again in that case. I thought that someone in that thread had managed to create an actual symlink, but then decryption still failed, which this commit could resolve. But that doesn't seem to be the case.

That's fine, we might end up still needing this PR once we manage to fix JGit's behaviour.

**Pull request closed without merging**
