### PR TITLE
Always refresh password list when navigating back

### PR DESCRIPTION
**Pull request by FabianHenneke**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description

Ends the practice of caching contents of folders on the navigation stack.

## :bulb: Motivation and Context

Caching and restoring directory contents introduces a lot of logic that can lead to bugs and goes against the spirit of the LiveData approach. Since file listing now happens on the IO thread and the scroll position is restored exactly, it is not even clear we need this kind of caching.

## :green_heart: How did you test it?
I verified that navigation still works as it previously did (and better in at least one edge case).

## :pencil: Checklist

- [x] I ran `./gradlew spotlessApply` before submitting the PR
- [x] I reviewed submitted code

### CODE REVIEW

**Comment by msfjarvis** [comment]
Do you wanna get rid of the caching? What would that entail for the end user?

**Comment by FabianHenneke** [comment]
> Do you wanna get rid of the caching? What would that entail for the end user?

Since navigating back does not trigger a search, but rather a simple file listing without filtering, I think that this should not cause a noticeable performance hit now that we are doing this on the IO thread. Furthermore, we have only recently begun to restore scroll positions approximately and the new implementation even does this exactly, which should more than make up for any lags.

I would vote for disabling it for the release. If there should be any real-world performance impact by this, we could revisit and rethink it (and all the edge cases).

**Comment by msfjarvis** [comment]
> > Do you wanna get rid of the caching? What would that entail for the end user?
> 
> Since navigating back does not trigger a search, but rather a simple file listing without filtering, I think that this should not cause a noticeable performance hit now that we are doing this on the IO thread. Furthermore, we have only recently begun to restore scroll positions approximately and the new implementation even does this exactly, which should more than make up for any lags.

Agreed.

> I would vote for disabling it for the release. If there should be any real-world performance impact by this, we could revisit and rethink it (and all the edge cases).

Wanna update this PR for that? I'd love for a broader feedback loop on this.

**Comment by FabianHenneke** [comment]
> Wanna update this PR for that? I'd love for a broader feedback loop on this.

I has already been in there from the start ;-)

**Comment by msfjarvis** [comment]
> > Wanna update this PR for that? I'd love for a broader feedback loop on this.
> 
> I has already been in there from the start ;-)


whaaaaaaa

**Pull request merged**
