### PR TITLE
WIP: Autofill for Android > Oreo (API 26)

### PR DESCRIPTION
**Pull request by l0rn**
This is my attempt to make use of the new autofill api

### CODE REVIEW

**Comment by zeapo** [comment]
@etiago maybe you could look into this PR so no conflict happens with your changes

**Comment by zeapo** [comment]
for the last item, do you have the package name of the activity you're trying to target?

**Comment by ReekyMarko** [comment]
Any update on this?

**Comment by l0rn** [comment]
I leaved it for now since Autofill inside browsers was still unsupported until Android P which made this feature still somewhat unattractive. Also I still have to address the issue of matching passwords to activities/webpage and probably introduce a manual select option. But I will probably pick this up during the next two months if no one else will. ATM I'm pretty busy with paid work

**Comment by ReekyMarko** [comment]
Thanks for the update! I can wait a bit longer since the whole pass ecosystem is easily the most flexible one out there. The autofill api would just be icing on the cake :innocent:

**Comment by zeapo** [comment]
@l0rn It's OK, you did an amazing job already. It's totally understandable that you don't have much time to work on this a little bit more.

I'll create a branch with your changes so someone else can continue to work on it.

**Comment by jessesimpson36** [comment]
Hey, I just wanted to ask about the progress on this. I may be able to help.

**Comment by IvanMalison** [comment]
@l0rn I'd be happy to work on this if you could give me som guidance on what needs to be done!

**Comment by jbaum98** [comment]
@l0rn I would also be happy to help out to make this happen.

**Comment by bkchr** [comment]
@IvanMalison did you make any progress on this issue?

**Comment by msfjarvis** [comment]
Superseded by #511

**Pull request closed without merging**
