### PR TITLE
WIP: Fix soft links

### LINKED ISSUE #636: [BUG] symlinks are clobbered by the app
**Describe the bug**
A password will fail to decrypt if it is a soft link as opposed to a normal file.

**To Reproduce**
1. Create a password that's a soft link to an existing password using `ln -s <passwd>.gpg softlink.gpg`
2. Pull the repository on device
3. Try to decrypt the password

**Expected behavior**
Password is decrypted and shown in the UI

**Device information (please complete the following information):**
 - Device: Google Pixel 2
 - OS: Android R DP1
 - App version 1.6.0-SNAPSHOT

**Additional context**

Relevant log snippet

```
E  onError getErrorId: 0
E  onError getMessage: No valid OpenPGP encrypted or signed data found!
```

### PR DESCRIPTION
**Pull request by Skrilltrax**
Fixes #636 

Always use the absolute file to decrypt passwords.

Reference : https://stackoverflow.com/questions/7281612/android-determining-a-symbolic-link

## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description
Always use absolute file to decrypt the password.

## :bulb: Motivation and Context
Fixes #636 

## :green_heart: How did you test it?
Haven't tested it yet.

## :pencil: Checklist

- [ ] I ran `./gradlew spotlessApply` before submitting the PR
- [ ] I reviewed submitted code

## :camera_flash: Screenshots / GIFs

### CODE REVIEW

**Comment by msfjarvis** [comment]
Doesn't work right now. I'll take over tomorrow and see if I can make a dent.

**Comment by FabianHenneke** [comment]
I somehow can't get symlinks to show up in Password Store on my phone, but this SO answer may contain the function you want to call, `toRealPath`: https://stackoverflow.com/a/28372122/297261

**Comment by msfjarvis** [comment]
> I somehow can't get symlinks to show up in Password Store on my phone, but this SO answer may contain the function you want to call, `toRealPath`: [stackoverflow.com/a/28372122/297261](https://stackoverflow.com/a/28372122/297261)

I believe that is Java 8 API which can't be used on API 23 :(

**Comment by FabianHenneke** [comment]
I went through the documentation and may have found an API level independent way to resolve symlinks. It is untested though since for some reason I can't get symlinks to show up in my Password Store repo.

**Comment by msfjarvis** [comment]
> I went through the documentation and may have found an API level independent way to resolve symlinks. It is untested though since for some reason I can't get symlinks to show up in my Password Store repo.

No dice, still very much broken.

**Pull request closed without merging**
