### PR TITLE
Add setting to save OpenKeychain auth keyid

### PR DESCRIPTION
**Pull request by msfjarvis**
Updated and rebased version of https://github.com/password-store/Android-Password-Store/pull/496 since @vexofp appears unavailable.

Co-Authored-By: Reagan Sanders <vexofp@gmail.com>

### CODE REVIEW

**Comment by msfjarvis** [comment]
I don't have a device that can test this so @zeapo you'll have to fill in.

**Comment by zeapo** [comment]
I'll test it tonight, thanks @msfjarvis

**Comment by msfjarvis** [comment]
I'll make the change

**Comment by msfjarvis** [comment]
> One small comment, the "Clear" option, when disabled does not change color, so it feels like it's clickable again.

I've changed it to be hidden instead, probably not the best UX but I guess it'll do for now.

**Pull request merged**
