### PR TITLE
Make APS buildable on F-Droid

### PR DESCRIPTION
**Pull request by FabianHenneke**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring

## :scroll: Description

Move `android-components:lib-publicsuffixlist` into the tree and set up an update flow for the Public Suffix List asset.

The code files are licensed under GPL-3.0.-only OR MPL-2.0 and unmodified from the original (except for an SPDX header at the top).

## :green_heart: How did you test it?
I verified that the build passes locally and ran `./gradlew app:dependencies' to verify that we are actually including the latest release of the android-components.

## :pencil: Checklist

- [x] I ran `./gradlew spotlessApply` before submitting the PR
- [x] I reviewed submitted code

### CODE REVIEW

**Comment by FabianHenneke** [comment]
This is blocked on the jitpack build timing out on more recent versions of `android-components`.

**Comment by FabianHenneke** [comment]
I have opened an issue with jitpack.io: https://github.com/jitpack/jitpack.io/issues/4204

**Comment by FabianHenneke** [comment]
@msfjarvis What I forgot about: This still requires moving the package name back into `app/build.gradle`. Could we do this in a separate PR since it will need to be done regardless of whether jitpack works out or not?

**Comment by msfjarvis** [comment]
> @msfjarvis What I forgot about: This still requires moving the package name back into `app/build.gradle`. Could we do this in a separate PR since it will need to be done regardless of whether jitpack works out or not?

Do it here for now, if Jitpack doesn't pan out we can start a new PR with that.

**Comment by FabianHenneke** [comment]
> Do it here for now, if Jitpack doesn't pan out we can start a new PR with that.

Done. There is nothing CI-related that I need to adapt, right?

**Comment by msfjarvis** [comment]
> > Do it here for now, if Jitpack doesn't pan out we can start a new PR with that.
> 
> Done. There is nothing CI-related that I need to adapt, right?

No CI should deal with everything just fine.

**Comment by msfjarvis** [comment]
According to [this](https://gitlab.com/fdroid/rfp/-/issues/1320#note_331543140) issue for [Dawn](https://github.com/Tunous/Dawn)'s inclusion into F-Droid, the distribution checksum field was a requirement so I just lumped it into this PR.

**Comment by msfjarvis** [comment]
Any progress here from Jitpack?

**Comment by FabianHenneke** [comment]
Unfortunately not. Last time they reacted within 5 hours, now it's been 5 days with no reply.

**Comment by msfjarvis** [comment]
> Unfortunately not. Last time they reacted within 5 hours, now it's been 5 days with no reply.

That's rather sad... If I automate the updation of PublicSuffixList data in this repository would it be feasible to stand up our own implementation of the methods we use?

**Comment by FabianHenneke** [comment]
Can't we just extract the current state of the Mozilla component with proper license attribution and freeze it, just updating the raw data from now on?

**Comment by msfjarvis** [comment]
> Can't we just extract the current state of the Mozilla component with proper license attribution and freeze it, just updating the raw data from now on?

Is the Mozilla licensing compatible with GPL 3.0?

**Comment by FabianHenneke** [comment]
> > Can't we just extract the current state of the Mozilla component with proper license attribution and freeze it, just updating the raw data from now on?
> 
> Is the Mozilla licensing compatible with GPL 3.0?

Ianal, but this seems to be fine as per https://www.mozilla.org/en-US/MPL/2.0/combining-mpl-and-gpl/ if we use a specific file header and don't copy in any of our existing GPL code.

**Comment by msfjarvis** [comment]
> > > Can't we just extract the current state of the Mozilla component with proper license attribution and freeze it, just updating the raw data from now on?
> > 
> > 
> > Is the Mozilla licensing compatible with GPL 3.0?
> 
> Ianal, but this seems to be fine as per [mozilla.org/en-US/MPL/2.0/combining-mpl-and-gpl](https://www.mozilla.org/en-US/MPL/2.0/combining-mpl-and-gpl/) if we use a specific file header and don't copy in any of our existing GPL code.

Alright then, I'll prep a Actions workflow.

**Comment by msfjarvis** [comment]
Works perflect :)

https://github.com/msfjarvis/Android-Password-Store/pull/1

**Comment by FabianHenneke** [comment]
Does every file in our tree have to be GPL or can we include unmodified files under other licenses? I would guess yes, but am not sure what our policy is.

**Comment by FabianHenneke** [comment]
I have force-pushed a slightly updated history and edited the description accordingly. Since we only needed four files from the Mozilla repo and could get away with no modifications (I simply did not copy a file with external dependencies we didn't need), there is also no need for a lawyer.

**Comment by msfjarvis** [comment]
> Does every file in our tree have to be GPL or can we include unmodified files under other licenses? I would guess yes, but am not sure what our policy is.

I don't think everything has to be GPL, what I'm seeing in this PR looks correct to me.

**Comment by FabianHenneke** [comment]
Let me verify that this actually builds on f-droid and then we can get it in.

**Comment by FabianHenneke** [comment]
@msfjarvis While this does build on F-Droid, the format of the public suffix file used by Mozilla differs from the widely available one and goes through some extra compression step. Can you change the workflow to get the list from https://github.com/mozilla-mobile/android-components/raw/master/components/lib/publicsuffixlist/src/main/assets/publicsuffixes and enable binary diffing to detect changes?

**Comment by msfjarvis** [comment]
Yeah I'll do that in half an hour or so, had to step out for a bit.

**Comment by FabianHenneke** [comment]
> Yeah I'll do that in half an hour or so, had to step out for a bit.

Thanks! No need to be quick here, we haven't skipped four major versions on F-Droid to be in a rush now ;-)

**Comment by FabianHenneke** [comment]
Thanks, I confirmed that the asset is now in the correct format and picked up by the in-tree lib-publicsuffixlist. 

I think this is good to go now. If you want, we could cut 1.7.3 and I would submit the F-Droid PR. Alternatively, we can wait for 1.8.0.

**Comment by msfjarvis** [comment]
> Thanks, I confirmed that the asset is now in the correct format and picked up by the in-tree lib-publicsuffixlist.
> 
> I think this is good to go now. If you want, we could cut 1.7.3 and I would submit the F-Droid PR. Alternatively, we can wait for 1.8.0.

I'd personally like to wait for 1.8.0 but we can certainly merge this in the mean time.

**Pull request merged**
