### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by FabianHenneke**

### CODE REVIEW

**Comment by msfjarvis** [comment]
Not really a fan of the English resources in untranslated locales, so I've turned it off. The default language mappings are also wrong but I can't seem to get that dialog to work, here's how it should look like if you can make the change.

image

**Comment by FabianHenneke** [comment]
Do we want to add other languages?

I mistakenly used `%two_letter_code%` first, moved to `%android_code%` now.

**Comment by msfjarvis** [comment]
> Do we want to add other languages?

Sure, [WireGuard](https://crowdin.com/project/wireguard) has a good set that has worked well.

**Comment by FabianHenneke** [comment]
I will play around with the integration until everything works fine, please ignore PRs until then. As the last step, I would change the config to use the actual `master` branch as base, but this can't be done automatically since it is protected.

**Pull request closed without merging**
