### PR TITLE
Migrate to Crowdin for localization

### PR DESCRIPTION
**Pull request by msfjarvis**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## :scroll: Description
Transifex seems to lack the userbase that Crowdin has in terms of translators which
affects the feasibility of keeping our business on it. Migrating to Crowdin allows
more people to contribute to the app, reducing the future chances of issues like
#839 cropping up again. I have elected to start the Crowdin project with no previous
translations because a large chunk of them were straight up outdated or wrong at this
point thanks to our continuous improvements and changes.

## :bulb: Motivation and Context
Transifex is not getting us localization momentum so we'll be giving Crowdin a shot.

## :pencil: Checklist

- [ ] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [ ] I reviewed submitted code
- [ ] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

## :crystal_ball: Next steps
We should probably also offer users the option of contributing to localization through an in-app preference.

### CODE REVIEW

**Comment by FabianHenneke** [comment]
Sorry for merging right away, I believe that crowdin's string.xml is outdated. I'm FabianHenneke there, if you invite me as a manager, I can update it.

**Comment by msfjarvis** [comment]
> Sorry for merging right away, I believe that crowdin's string.xml is outdated. I'm FabianHenneke there, if you invite me as a manager, I can update it.

Yeah I was gonna ask for your username. Sent a manager invite.

**Comment by FabianHenneke** [comment]
Should we set up crowdin's GitHub integration?

**Comment by msfjarvis** [comment]
> Should we set up crowdin's GitHub integration?

Yeah I think we should, if manager permissions don't let you configure it on Crowdin I'll do it in a few hours. We should probably also either sync our translations to Crowdin or just delete them all and start from scratch.

**Comment by FabianHenneke** [comment]
> > Should we set up crowdin's GitHub integration?
> 
> Yeah I think we should, if manager permissions don't let you configure it on Crowdin I'll do it in a few hours. We should probably also either sync our translations to Crowdin or just delete them all and start from scratch.

I think I can do it, will give it a try now.

**Pull request merged**
