### PR TITLE
Significantly improve app theming

### PR DESCRIPTION
**Pull request by msfjarvis**
## :loudspeaker: Type of change

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature
- [ ] Refactoring

## :scroll: Description
Ensure all text input outlines are tinted with the accent color, and the text handle cursor is always visible.

## :bulb: Motivation and Context
The dark outline and invisible text handle just looked terrible.

## :green_heart: How did you test it?
Visual

## :pencil: Checklist

- [x] I ran `./gradlew spotlessApply` before submitting the PR
- [x] I reviewed submitted code

## :crystal_ball: Next steps

Maybe replace the spinners with a [MaterialButtonToggleGroup](https://developer.android.com/reference/com/google/android/material/button/MaterialButtonToggleGroup) or [Chips](https://material.io/components/chips)?

### CODE REVIEW

**Comment by msfjarvis** [comment]
> I like the new style. It does not seem to apply to dialogs (e.g., the folder creation dialog) though, where the EditText has a dark grey background.

I think I did that intentionally since it looked nicer there but I have no hard stance on it so I'm down to make it all uniform if you prefer that.

> I think that ChipGroups would work really well for the `Protocol` and the `Authentication Mode`.

I began experimenting with the button toggle group, [this](https://i.imgur.com/LnULsud.png) is how it looks right now. Open to chips as well.

**Comment by FabianHenneke** [comment]
> I think I did that intentionally since it looked nicer there but I have no hard stance on it so I'm down to make it all uniform if you prefer that.

I think I would prefer it to be consistent since the color of the text field is otherwise more similar to the dimmed background than to the rest of the dialog.
 
> I began experimenting with the button toggle group, [this](https://i.imgur.com/LnULsud.png) is how it looks right now. Open to chips as well.

The screenshot fully convinced me, this is great. Nit: The left margin of the lower toggle group seems off.

**Comment by msfjarvis** [comment]
> > I think I did that intentionally since it looked nicer there but I have no hard stance on it so I'm down to make it all uniform if you prefer that.
> 
> I think I would prefer it to be consistent since the color of the text field is otherwise more similar to the dimmed background than to the rest of the dialog.

Alright I'll fix this in a minute.

> > I began experimenting with the button toggle group, [this](https://i.imgur.com/LnULsud.png) is how it looks right now. Open to chips as well.
> 
> The screenshot fully convinced me, this is great.

Awesome. I'm also taking this time to begin address the GitActivity part of #680.

> Nit: The left margin of the lower toggle group seems off.

Yeah I noticed that as soon as I sent the screenshot. Fixed it locally.

**Comment by msfjarvis** [comment]
@FabianHenneke

**Comment by Skrilltrax** [comment]
This looks good 👍

Change light theme colours to material white I guess ?

**Comment by msfjarvis** [comment]
> This looks good 
> 
> Change light theme colours to material white maybe ?

Eh I'm not too sure about whitewashing. I kinda like the app the way it is.

**Comment by FabianHenneke** [comment]
I don't have system-wide dark mode on my phone yet, but the light mode version of the create folder dialog is now exactly the way I had imagined it.

I don't really have an opinion re material white.

**Comment by msfjarvis** [comment]
> I don't have system-wide dark mode on my phone yet, but the light mode version of the create folder dialog is now exactly the way I had imagined it.

Great reminder to add the preference option for it!

**Comment by msfjarvis** [comment]
@FabianHenneke give it a try :smile:

**Comment by FabianHenneke** [comment]
> @FabianHenneke give it a try

@msfjarvis Very nice, I'll run APS in dark mode from now on :+1:

**Comment by msfjarvis** [comment]
> > @FabianHenneke give it a try
> 
> @msfjarvis Very nice, I'll run APS in dark mode from now on

image


P.S. review pls?

**Comment by msfjarvis** [comment]
> I'm missing the toggle groups for protocol/authentication, but what I can see is ready to be merged.

It's part of the [feature/revamp-git-setup](https://github.com/android-password-store/Android-Password-Store/tree/feature/revamp-git-setup) branch that includes the breakdown of GitActivity. It's gonna take a while.

**Pull request merged**
