### PR TITLE
Upgrade runtime dependencies

### PR DESCRIPTION
**Pull request by msfjarvis**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description
Run `gradle dependencyUpdates` and upgrade all dependencies that are safe to do so.

## :bulb: Motivation and Context
Upgrading to latest versions brings important bugfixes (AGP 3.6.3 fixes a rather problematic cache hit scenario around {View,Data}binding that should speed up our builds) and new features (such as material transitions that will hopefully replace [EmitExpandableTransformationBehaviour.kt](app/src/main/java/com/zeapo/pwdstore/widget/fab/EmitExpandableTransformationBehaviour.kt)).

## :green_heart: How did you test it?
Manually go through the app and confirm things work as before.

## :pencil: Checklist

- [x] I ran `./gradlew spotlessApply` before submitting the PR
- [x] I reviewed submitted code

## :crystal_ball: Next steps
Some new deprecations here that need to be addressed.

### CODE REVIEW

**Comment by FabianHenneke** [comment]
Just an announcement: We may be able to update our AndroidFastScroll dependency before the release since I have submitted a PR that fixes the selection on fast scroll issue (https://github.com/zhanghai/AndroidFastScroll/pull/17).

**Comment by msfjarvis** [comment]
> Just an announcement: We may be able to update our AndroidFastScroll dependency before the release since I have submitted a PR that fixes the selection on fast scroll issue ([zhanghai/AndroidFastScroll#17](https://github.com/zhanghai/AndroidFastScroll/pull/17)).

The release isn't due for another 3 days so I guess we can wait for this. I'll take the time to transition to the new motion system.

**Comment by msfjarvis** [comment]
Force pushed with lint fixes

**Comment by msfjarvis** [comment]
Going to push the UI changes in a separate PR, this can go in when https://github.com/zhanghai/AndroidFastScroll/pull/17 is published or the release is due, whichever happens earlier.

**Comment by FabianHenneke** [comment]
> Going to push the UI changes in a separate PR, this can go in when [zhanghai/AndroidFastScroll#17](https://github.com/zhanghai/AndroidFastScroll/pull/17) is published or the release is due, whichever happens earlier.

There is also the option of including the patch (which is just a drop-in replacement for RecyclerView) manually if upstream shouldn't release soon enough. Do you think that the scoll/select bug would warrant that?

**Comment by msfjarvis** [comment]
> > Going to push the UI changes in a separate PR, this can go in when [zhanghai/AndroidFastScroll#17](https://github.com/zhanghai/AndroidFastScroll/pull/17) is published or the release is due, whichever happens earlier.
> 
> There is also the option of including the patch (which is just a drop-in replacement for RecyclerView) manually if upstream shouldn't release soon enough. Do you think that the scoll/select bug would warrant that?

I think we _should_ patch manually for the time being if that's a possibility.

**Pull request merged**
